# Generated by Django 4.1.2 on 2022-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('categoria', models.CharField(max_length=50)),
                ('fabrica', models.CharField(max_length=50)),
            ],
        ),
    ]
